Eliminate compiler warning message
error: passing argument 1 to restrict-qualified parameter aliases with
argument 3. Since in sprintf function the input argument is same as the
output argument. Therefore I use snprintf instead.